### ISSUE TITLE
you can't override the preconfigured casper instance in a test environment

### ISSUE THREAD

**Issue by lauterry** [iamchrismiller/grunt-casper#47]
Hi

I have the following configuration : 

```
casper: {
            options: {
                test : true
            },
            files: [
                'test/integration/**/ouverture.js'
            ]
        }
```

When I run `grunt casper`

I have the following error : 

"Fatal: you can't override the preconfigured casper instance in a test environment.
Docs: http://docs.casperjs.org/en/latest/testing.html#test-command-args-and-options"

**Comment by Redsandro** [comment]
Thanks @lauterry, this solved my problem. :+1:

**Comment by huyb1991** [comment]
Thanks @lauterry, this solved my problem, I just follow example code on [CasperJS homepage](http://casperjs.org/)
