### ISSUE TITLE
Aborts when setting engine to 'slimerjs'

### ISSUE THREAD

**Issue by brandondurham** [iamchrismiller/grunt-casper#55]
As far as I can tell SlimerJS is installed and working properly. However, when I change the `engine` option in grunt-casper to `slimerjs` I get an "Aborted due to warnings." message in the console with no error details. Here is What I'm seeing in the console:

```
Running "casper:functional" (casper) task
>>
Casper Task 'casper:functional' took ~1393ms to run
Warning: Task "casper:functional" failed. Use --force to continue.

Aborted due to warnings.
```

And here is what I have in my Gruntfile.js:

```
casper: {
    options: {
        test: true,
        includes: './bower_components/jquery/dist/jquery.min.js',
        engine: 'slimerjs'
    },
    functional: {
        options: {
            args: ['--rooturl=http://<%= connect.options.hostname %>:<%= connect.options.port %>/']
        },
        files: {
            'test/results/functional-results.xml': [
                'test/spec/**/*.js'
            ]
        }
    }
},
```

Any idea what might be happening?

**Comment by icd2k3** [comment]
I'm still having this issue with 0.4.1, phantomjs 2.0.0, casperjs 1.1.0-beta 3, and slimerjs 0.9.5 - when I run my tests with the phantomjs engine they work fine, but when trying slimer as an engine I get:

`Aborted due to warnings.` with no details

Any ideas?
