### ISSUE TITLE
missed test files randomly

### ISSUE THREAD

**Issue by ttback** [iamchrismiller/grunt-casper#65]
I am trying to run all the .js files under smoke dir with grunt-casper, but sometimes it runs only 2 of the js files

grunt-casper config:

```
casper : {
         smoke : {
            options : {
              test : true,
              "fail-fast": true,
              "log-level": "info",
              "verbose": true,
              "parallel": false,
            },
            files : {
              './smoke/casper-results.xml' : ['test/smoke/*.js']
            }
          }
        }

```

Test code (the files share the same code to test out grunt-casper) I can't see anything wrong with it atm. I don't think it's related to the request to url, since the "running test" message is not even output for the missing test.

```
casper.test.begin(" test", 1, function(test) {
    casper.start();

    console.log("running test);
    casper.open(url, {
        method: 'head'
    });

    casper.then(function(response) {
        test.done();
    });

    casper.run(function() {
        casper.exit();
    });
});

```

**Comment by lgiraudel** [comment]
Try to replace `casper.exit()` by `casper.test.done()`

**Comment by ttback** [comment]
@lgiraudel thanks, that worked
